application:
  apn:
    certificate: classpath:files/certificate.p12
    password:
    bundle-id: id.ac.its.my.wali
  fcm:
    credentials: classpath:files/credentials.json
  security:
    public-key: classpath:files/jwt.pub
server:
  port: ${PORT:8080}
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
